name: Frontend build pipeline

on: 
  push:
    branches:
      - frontend

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Installing packages
        run: npm install
      - name: Creating a build
        run: npm run build
      - name: Linting
        run: npm run eslint
